services:
  echo:
    build: .
    container_name: echo-container
    runtime: nvidia 
    network_mode: "host"
    environment:
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./src:/app/src/
      - './src/logs:/isaac-sim/kit/logs/Kit/Isaac-Sim Streaming/5.0/'
    # command: ["./run_app.sh"]

    tty: true
    stdin_open: true
    entrypoint: /bin/bash